name: Python
injections:
  coc_settings:
    - '"python.jediEnabled": false'
    - '"python.linting.mypyEnabled": true'
    - | 
      "python.linting.mypyArgs": [
            "--strict",
            "--ignore-missing-imports"
          ]
  nvim_plug:
    -  "Plug 'neoclide/coc-python', {'do': 'yarn install --frozen-lockfile'}"

commands:
  pre_template:
    - pip3 install python-language-server[all]
    - pip3 install pynvim

