name: fzf
injections:
  nvim_plug:
    - Plug 'junegunn/fzf'
    - Plug 'junegunn/fzf.vim'
  nvim_config:
    - '" ---------------'
    - '"  FZF'
    - '" ---------------'
    - nnoremap <silent> <space>p :FZF<cr>
    - nnoremap <silent> <space>P :FZF ~<cr>
    - nnoremap <silent> <space>b :Buffers<cr>
    - '" Find text in current buffer'
    - nmap <space>/ :<C-u>BLines<cr>
  bash:
    - "export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g \"\"'"
  fish:
    - "set -x FZF_DEFAULT_COMMAND 'ag --hidden --ignore .git -g \"\"'"
  
commands:
  pre-template:
    - sh $LAYER_DIR/install_fzf.sh
