# Source from .bash_profile by doing
#
# source /path/to/this/file

# Correct colors
export TERM=xterm-256color
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'

export PATH=$PATH:{{ env.repo_dir }}/bin
