name: Fish shell config
templates:
  - file: config.fish
    destination: ~/.config/fish/config.fish
commands:
  pre-save:
    - curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
    - curl -L https://get.oh-my.fish | fish

